### ISSUE TITLE
README.rst on PyPI has incorrect syntax

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#108]
See https://pypi.python.org/pypi/ld/0.5.0

Issues:

- Links in markdown syntax don't work (shows link source code).
- Headings introduced with `##` don't work (shows `##` in text).
- `...shell` syntax to get highlighting as shell commands does not work (shows `shell` in text).
- Using back quotes to get links to standard Python stuff, or at least monospaced font, does not work (shows italic font and cuts off things like parenthesis).
- Multi-line example code does not stay on separate lines.
- ... more?

**Comment by nir0s** [comment]
I suggest that instead of maintaining both the rst and the md, we provide a static link to the github repo from the rst file.

**Comment by nir0s** [comment]
#110 solves this.
