### ISSUE TITLE
info() converts to lower case

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#11]
The machine readable part of the information returned by info() is already in lower case. Things like codename and name are for human consumption and are most useful when their case is preserved, IMO. I suggest not to translate everything to lower case in info(), but just to aggregate the information into a dictionary.

Edit: Removed invalid second issue about missing name (I looked at the docstring).

**Comment by nir0s** [comment]
Well, name is not there and I can tell you that we're using codename for automation purposes. Care to explain why you think it's better to preserve the case? In my experience, all I do when I see these is to `.lower()` them to not deal with their case.

**Comment by andy-maier** [comment]
* On using the codename for machine readable / automation purposes: I thought about this and here are some reasons I found:
    - The codename is a fragile construct to parse. For example, the /etc/os-release file does not even have a field for it, and it is not guaranteed to be part of its VERSION field, and the code that parses it from the VERSION field goes by the heuristic of some specific cases. You brought up the SuSE example in another issue, where they have "(x86_64)" at the end of the line of the distro release file, syntactically matching the codename.
    - Some distros are being inconsistent with their codename. For example, Ubuntu 14.04 defines its codename as "Trusty Tahr" in the VERSION field of /etc/os-release, and as "trusty" in the output of the lsb_release command.
    - Automation based on the codename could as well be done based upon the version. (Assuming of course the version is detailed enough, which does not seem to be the case in every distro. For example, Debian 8.2 has an /etc/os-release file with VERSION_ID="8" and an /etc/debian-version file containing the line "8.2". By the way, this is a case where the lsb_release command is supported and returns "Release: 8.2" without having an /etc/lsb-release file around. It has no other release files I'm aware of, so it must work off of the /etc/debian-version file.)

  So I arrived at the conclusion that the codename is better not used for machine readable purposes, i.e. its other role is to be a human readable string. Let's rather fix the cases where the version is not detailed enough, by special casing them.

* On lower case values in info(): I was wrong when I stated that all values but name and codename are already in lower case. By the way, "name" is in the code - it is just not in the example in the description.

  What I'm concerned about is the inconsistency between accessing the values with info() which currently translates them all to lower case, and accessing them one-by-one (e.g. with codename()) or with the mechanism-specific *_info() functions which do not translate them to lower case in all cases. IMO, info() should just be the aggregate way of accessing the same information one can access one-by-one.

I think some values should in fact be in lower case (everything but codename and name), but that should probably be done where the values are created, and not dependent on how they are accessed.

**Comment by nir0s** [comment]
All good points. 

* I've removed `codename` from there but I will be keeping `name` as `id` is not always provided.
* You're right about inconsistency. I'll remove all `.lower()`ing in the info.
* I tend to agree that they should all be in lower case.. but I'm not sure how that affects users. I suggest we keep it as it is and see later on once we have more people using this and giving feedback.

**Comment by nir0s** [comment]
Do we want to close this issue until we've figured out if lowercase vs. uppercase is at all a problem right now? As it is currently implemented, there are no consistency issues.

**Comment by andy-maier** [comment]
I agree to close it.
