### ISSUE TITLE
info() result does not include codename

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#112]
The documentation for `info()` shows a `codename` key in its result dictionary.
The code for `info()` does not produce that key.
The testcases for `info()` so far did not catch that discrepancy.

Proposal:
* Change `info()` implementation to include a `codename` member in its result.
* Improve the `info()` testcases to verify that.

**Comment by andy-maier** [comment]
Addressed that in PR #113.

**Comment by nir0s** [comment]
This was intentional. The purpose of info was to provide only machine actionable information, which is why codename and "pretty" versions/names were left out. I don't mind if codename was there, but then I think we need to also provide "pretty" there.

**Comment by andy-maier** [comment]
Ok, I'll update PR #113 to add a `pretty` parameter to `info()`.
