### ISSUE TITLE
Docstrings missing for *_info()

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#12]
The functions os_release_info(), lsb_release_info(), and distro_release_info() are public but do not have a docstring currently.

For distro_release_info(), the returned dictionary can be described, because the ld code generates it.

For os_release_info(), I suggest to point to http://www.freedesktop.org/software/systemd/man/os-release.html for a definition of the fields, and to mention that the field names are converted to lower case.

For lsb_release_info(), the information items returned by the lsb_release command have not changed between LSB 1.0 and LSB 5.0, so I think it is safe to describe them explicitly. A pointer to the lsb_release command as described in the LSB 5.0 standard would not hurt, though: http://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/lsbrelease.html

**Comment by nir0s** [comment]
Done in https://github.com/nir0s/ld/tree/various-fixes-and-optimizations but still basing on /etc/lsb-release. Once we decide about the lookup hierarchy, this might change.

**Comment by andy-maier** [comment]
Great!
Let's close this one and handle any remaining changes along with the discussion on lsb_release command vs /etc/lsb-release file.
