### ISSUE TITLE
Test results 12/22

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#13]
Hi, this is not an issue.
Attached is a file with the test results on some distros:
[testresults.txt](https://github.com/nir0s/ld/files/69594/testresults.txt)

Some things to note (some of which may in fact be issues):
* On Arch Linux, there is no version defined. This is probably a result of their philosophy not to have a version, but instead to always ensure everything is at the latest level. It would still be nice to be able to say at what level the system was at a particular point.
* On CentOS 6.7, the ld parsing results in an empty version and codename, even though there are distro release files that define that, and it is able to figure out that the distro name is "centos". Strangely enough, the distro_release_info() is entirely empty, which it should not be given that info() finds out the name. I did not investigate this further.
* On Debian 8.2, the version is "8", because the VERSION field in the os-release file says so. However, the lsb_release command returns "8.2" for the version. there is no /etc/lsb-release file, but an /etc/debian-version file with the line "8.2" in it. This might be a good reason to special-case the distro in order to find the more detailed version.
* On Ubuntu 14.04, the release files specify only "14.04" as a version in the version fields, but specify "14.04.3" in the pretty name in both the os-release and lsb-release files. It would be nice to special-case that too to determine the more detailed version.

**Comment by nir0s** [comment]
I released 0.2.0 to PyPI with all of the changes we discussed up until now. Let's continue with this one from here.

**Comment by andy-maier** [comment]
Agreed. I'll post new results based upon the latest master, at some point.
