### ISSUE TITLE
Overall distro test missing

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#20]
The unit test tests the distro release file, the OS release file, and the lsb_release command independently from each other.

However, the ld.info() method and the underlying specific methods depend on these three sources of information coming together in a particular combination, for each distribution. For example, the precedence rules implemented by these functions are currently untested.

I suggest to add a class for testing all the combinations, for the distros that are in test scope.

I intend to come up with a pull request for that, shortly.

**Comment by andy-maier** [comment]
It seems to me that the data structure in the tests/resources directory needs to be changed in order to accomplish this. For example, the current files that have release numbers in their file names don't work, because part of the algorithm is to look at the file name of the distro files (and they are not used in the tests currently). Also, part of the algorithm is to list files according to a search pattern and to process the list in a sorted order (the algorithm also includes a lookup in the DIST_TO_BASE which is why the test still works, but I think this places too much knowledge about the implementation into the test).

My proposal for a new file structure is:

    +-- resources
        +-- distros
        |   +-- ubuntu14
        |   |   +-- bin
        |   |       +-- lsb_release
        |   |   +-- etc
        |   |       +-- os-release
        |   |       +-- ubuntu-release
        |   |       +-- lsb-release
        |   + ...
        +-- special
            +-- empty-release
            +...    # and other corner cases

The files only exist if they exist in the real distro, and if the real distro has symbolic links, that is represented as well in the file structure (for example, CentOS 7 has a /etc/centos-release file and symbolic links /etc/system-release and /etc/redhat-release that point with a relative file name to /etc/centos-release. In some distros, /etc/os-release is a symbolic link to /usr/lib/os-release, that would be represented as well, and it is important to test whether symbolic links are found when searching for the file pattern.

The bin/lsb_release command is a shell script that exists in two versions: one with (like Ubuntu 14) and one without (like CentOS 7) the <distro>/etc/lsb-release file. Both versions only support the -a option. I have written both versions already, and these shell scripts are both quite short.

Alternatively, we could have one version of the lsb_release script that uses an lsb-release file and we vary the location of the lsb-release file between <distro>/etc and <distro>/hidden, depending on whether the distro has it in /etc or not.

The reason to be so picky about the presence of the lsb-release file is that it matches the file search pattern that is used, and sorts before or after the distro release file, depending on the distro name. Again, the check for DIST_TO_BASE makes sure it is never used when the distro release file is being identified, but again I think depending on that circumstance in the test code is too much of a white box.

The existing unit tests would simply use the files at their new locations, and a new test class would be written to perform a realistic distro test, by setting its PATH to include <distro>/bin, where it finds the lsb_release command, and by looking up <distro>/etc instead of /etc. I have not started writing this new test, yet, but am offering to do so.

I have created the new file structure locally, and have started to verify (for the distros in DIST_TO_BASE) that they contain exactly what the real distro contains. I'm nearly through with that verification by now.

What do you think about the proposal?

**Comment by nir0s** [comment]
I've reviewed the new structure and merged it as it seems like a good idea to me especially considering the fact that there will always be a one-to-one relationship between a single resource in the tree and a distribution. 

Your suggestion for using lsb_release (of course, as long as we're certain the `-a` flag is always present) seems like a better idea to me as it removes the overhead of maintaining an additional parser.

I would greatly appreciate the contribution as I can't seem to get to it right now.

**Comment by andy-maier** [comment]
Nir,
I have coded the overall test and can create a merge request for it right away. The thing is, the overall test cases have unexpected results that I first wanted to analyze, but I could do that in another separate step.

**Comment by andy-maier** [comment]
I just wanted to clarify that the merge request #28 does everything I had in mind, including analyzing the expected results and fixing those that needed a fix.

It is ready for review and merge and would solve this issue.

**Comment by nir0s** [comment]
Thank you. Please solve the conflicts and i'll review everything. Thanks!

**Comment by andy-maier** [comment]
All conflicts resolved, see PR #28.
