### ISSUE TITLE
ValueError exception with parsing lsb_release output

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#21]
**Problem:**
I found this issue on CentOS 7 with the lsb_release command from the standard repos. It is likely to happen on all distros that report LSB compliance information.

If the lsb_release command reports LSB compliance information in its first line, the value on the right side of the delimiting colon likely contains more colons. For example, on CentOS 7:

    LSB Version:    :core-4.1-amd64:core-4.1-noarch

This causes an exception:

    File "/media/ds12_home_andi/Projects/Python/ld/repo/ld/ld/__init__.py", line 122, in _parse_lsb_release
    k, v = obj.strip('\n').split(':')
    ValueError: too many values to unpack

**Proposed solution:**
This can be fixed by limiting the number of splits to 1:

    k, v = obj.strip('\n').split(':', 1)

**Comment by nir0s** [comment]
Sounds good to me.

**Comment by nir0s** [comment]
btw, I'm obviously not going through all possible scenarios right now due to time constrains so if we stumble upon any other problematic pattern, we'll deal with it.

**Comment by vbraun** [comment]
This breaks all Redhat distros, it would be great to make another release with the fix...

**Comment by Ofekmeister** [comment]
Is this fixed for Redhat distros?

**Comment by nir0s** [comment]
We'll release a version to pypi today that fixes it.

**Comment by Ofekmeister** [comment]
Great, thanks!
