### ISSUE TITLE
Parsing of distro release file with trailing newline does not match

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#22]
**Problem:**
While looking at the *-release files of real distros, I found that they typically have a trailing newline in the /etc/<distro>-release file.

This causes the new parsing algorithm you integrated to result in a non-match. Sorry for not finding that earlier.

**Proposed solution:**
One way of fixing this is to strip whitespace before matching in _parse_release_file(). Whitespace is stripped instead of just newline, to be on the safe side in case of trailing blanks or tabs.

    -        m = _release_version.match(content[::-1])
    +        m = _release_version.match(content.strip()[::-1])

Of course, as an alternative one could also make the _release_version regexp tolerant against trailing whitespace... don't know what performs better.

**Comment by nir0s** [comment]
Well.. If we do that in the regexp it will not be failsafe in case if unknown additional info in the string. Your first solution makes more sense to me for now.
