### ISSUE TITLE
Exception when lsb_release returns no LSB information

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#26]
When the lsb_release command is present, and when it returns no LSB conformance information, its first line usually (i.e. on real distributions) reads: 

    No LSB modules are available.

Because this does not contain any colon, the following code in _parse_lsb_release() raises an exception about not enough items in the returned tuple:

        props = {}
        for obj in content:
            k,v = obj.strip('\n').split(':', 1)         # raises exception when no colon in obj
            props.update({k.replace(' ', '_').lower(): v.strip()})
        return props

The following code addresses that:

        props = {}
        for obj in content:
            kv = obj.strip('\n').split(':', 1)
            if len(kv) != 2:
                # Ignore lines without colon.
                continue
            k,v = kv
            props.update({k.replace(' ', '_').lower(): v.strip()})
        return props

**Comment by nir0s** [comment]
lgtm
