### ISSUE TITLE
Version sometimes looses precision

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#29]
**Problem:**
I have seen one case where the defined priority of first os-release, then lsb_release, then distro release file, causes version() to return just the major version, when the system actually also has a minor version available. So we do not return all possible version detail, i.e. we "loose some precision".

The case I have seen is Debian 8.2, and that case is actually represented in the new test structure exactly as I have seen it on a real Debian 8.2 system:

  * /etc/os-release file defining VERSION=8, VERSION_ID=8
  * /etc/debian-version file containing just "8.2"

The current code simply goes by priority.

**Solution:**
If the code would be changed to go by best precision (out of all available sources), this could be addressed. The downside of such a solution is that it makes inconsistencies between the multiple sources even harder to understand, particularly if the inconsistency is not just more or less precision but even contradictions in the version parts that are available in multiple sources).

I think however, in the end it would be good to use the highest available precision for the version.

**Comment by andy-maier** [comment]
Because this would change the content of version(), I think this should be resolved before we declare the project as being ready.

**Comment by nir0s** [comment]
I don't know.. I tend to want to go with the more explicit, more standardized, less precise solution for two reasons:

1. precision will have to be backward compatible with things that will not be a part of the common standard at some point. For instance, of Debian decided to drop `.2` in os-release, this means that when debian 12 comes out, if they decide to leave behind `debian_version` for some reason, we will be looking at things that are not a part of the standard they chose to go with.
2. I'm not familiar with a clear definition of precision in this case. That is, i've seen a `debian_version` file with only `81` (being 8.1). I'd rather stay away from assumptions. If you're familiar with a unified standard on top of which we can create a precision algorithm, let's consider it.

**Comment by nir0s** [comment]
I just want to note that users have full access to the parsed information anyway so, potentially, they should be able to access the version fields everywhere in the hierarchy. That would make me feel safer as users can code their way into understanding whether they need the most precise one or not based on their needs without us makes assumptions for them.

**Comment by andy-maier** [comment]
I see your point about the problem of parsing sources such as debian-version.

So let me change the proposal: We could use only the (up to) 3 information sources we parse right now, and use the version out of those with the best precision.

For example, Debian 8 has this:
* "lsb_release -r -s" returns: 8.2
* /etc/os-release defines: VERSION_ID="8"
* no distro release file

The current "fixed priority approach" causes version() to return 8, the new "best precision" approach would compare the two available versions and return 8.2 as the more precise one. The debian_version file would not be used in that approach.

How does that sound?

**Comment by nir0s** [comment]
`debian_version` was somewhat of an example. It's not the only problem. The problem is that looking for the best precision is in itself ambiguous. Let's say that you're on RHEL 7 and found the os-release file. Now you rely on os-release to retrieve any relevant information. `ld`, in that case, looking for the best precision will disregard the fact that every other piece of information was taken from os-release. 

The ambiguity begins where you don't know where information will be extracted from. I'd rather have a single source of truth where possible and allow the user to go the extra mile instead of doing it for the user but leaving them scratching their heads.

I might be taking this too far, and I also might be basing this solely on my intuition, but I think it would cause more confusion than value.

What do you think?

**Comment by andy-maier** [comment]
I can definitely see both sides here.

How about a compromise: Would you be opposed to leaving `version()` as it is now, and adding a new `best_version()` that returns the most precise version, and documents well enough in its description that it may use a different source than the other methods?

**Comment by nir0s** [comment]
That's actually a great idea. I'll go for that.

**Comment by andy-maier** [comment]
This issue is addressed by PR #52.
