### ISSUE TITLE
distribution  == "Debian GNU/Linux"

### ISSUE THREAD

**Issue by vbraun** [nir0s/ld#3]
I've been trying it on various distros with good results, but on Debian I get an extra GNU/Linux in the distro name. Strictly speaking that is correct, but I think the ideal output would be just "Debian". Thoughts?
~~~~
$ python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ld
>>> ld.linux_distribution()
('Debian GNU/Linux', '8', 'jessie')
~~~~

**Comment by nir0s** [comment]
Can you try `ld.linux_distribution(full_distribution_name=False)` ?

**Comment by vbraun** [comment]
~~~~
>>> import ld
>>> ld.linux_distribution(full_distribution_name=False) 
('debian', '8', 'jessie')
~~~~

**Comment by nir0s** [comment]
that makes sense. `linux_distribution` is supported to return the full name by default.. but I agree, it would make more sense if it returned "Debian" with a capital D instead.

**Comment by nir0s** [comment]
Well, CentOS return "CentOS Linux" as the full name, so maybe Debian GNU/Linux makes sense.
