### ISSUE TITLE
"tests" is a subdirectory of the "ld" module

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#33]
Currently, the test cases are in a "tests" subdirectory in the directory for the "ld" package, as if it was a sub-package.

I suggest to move it up one level.

This is not something that would affect the public interface.

**Comment by andy-maier** [comment]
Merge request #33 is ready for review and resolves this issue.

**Comment by andy-maier** [comment]
In addition (and not in the merge request #33), I think the __init__.py file in the tests directory should be removed.

**Comment by nir0s** [comment]
I tend to put tests for a package within the specific package.. but since this is very stripped down, I don't have an objection.
