### ISSUE TITLE
Generated documentation is missing

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#34]
The docstrings are pretty good at this point, but it would be good to generate documentation from them, instead of having the separately maintained documentation in the README.md.

**Comment by nir0s** [comment]
After the entire thing is ready I intend to sphinx it and have it hosted on rtd.

**Comment by andy-maier** [comment]
PR #57 is a first stab at Sphinx documentation.

**Comment by andy-maier** [comment]
Addressed by PR #57.
