### ISSUE TITLE
Unreliable id() and meaning of base()

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#36]
There is not a reliable distro ID string currently. The result of the id() method is not always reliable, and the result of the base() method is somewhat more reliable, but its meaning is not entirely clear.

Example for CentOS/RHEL/Fedora/Oracle (return values shown have been taken from the TestOverall test cases, which have been verified to represent the situation in the real distros, so 
this should represent the actual behavior on these distros):

    Distro         id()      base()
    RHEL 6.5       redhat    rhel
    RHEL 7.0       rhel      fedora
    Fedora 23      fedora    fedora
    CentOS 5.11    centos    rhel
    CentOS 7.0     centos    rhel
    Oracle 7.1     oracle    rhel

Issue: The id() value between RHEL 6.5 and RHEL 7.0 changes.
Issue: CentOS is the open source distro of RHEL, but is it "based on" RHEL, or not rather based on Fedora?
Issue: Is Oracle really based upon RHEL in the sense that RHEL's source code is the input for Oracle, or is it not rather using CentOS's source code (I did not research it, but using RHEL does not sound plausible to me).

It seems to me that what we need is:

1) a more reliable id() value, that is normalized to a certain degree, e.g. by a mechanism similar to the DIST_TO_BASE dictionary, but in such a way that Oracle, RHEL, Fedora, CentOS would remain separate strings, and the string for each distro would not suddenly change in a new release, just because the distro moves to a new type of release file (RHEL 7.0 introduced /etc/os-release, which caused this change).

2) a better semantic definition on what base() really means. For example, does it denote:
   a) where the source code comes from (RHEL comes from Fedora, CentOS comes from RHEL, Oracle comes from xxx)?
   b) some sort of family (Fedora, RHEL, CentOS, Oracle would all be the same family)?
   c) something similar to like()? Note that the implementation of base() uses the result of like() for distros that are not in DIST_TO_BASE, but like() is using the LIKE attribute in /etc/os-release which sometimes contains more than one distro ID. If we stick with using like() as the default, then the description of base() should mention that it may end up returning more than one string.

Comments / Opinions?

**Comment by andy-maier** [comment]
This should be resolved before the project is considered ready.

**Comment by nir0s** [comment]
I tried to think of a use case in which base could be used to make a decision and I can't come up with one. I don't want boilerplate code with dealing with something that doesn't provide value so I'd get rid of it and just stick with `like` based on whatever os-release provides. Considering that most notable os distros are now moving towards that standard, I think we can safely assume that most users can do with `like`. It seems to me like anything we can do to fill up `base` would be too arbitrary as there might be ambiguities with regard to which distro belongs to which base.

Regarding `id`, I agree. We should perform specific mapping which will NOT be backward compatible but rather relying on os-release's provided ID by default so that we don't force the user to use an ID that is no longer officially supported.

Thoughts?

**Comment by andy-maier** [comment]
Nir, on reliable ID: I'm not sure I fully understand what you mean with specific mapping vs relying on os-release. Do you argue for a mapping in order to have a reliable ID returned by id(), and the argument is just about which value to use in cases where we know it changed?

On dropping base(): I agree to frop it, if we can find a way to make id() reliable.

**Comment by nir0s** [comment]
Yes. I argue that we should map a an ID to a base so that if we see `redhat` it will be mapped to `rhel`. What I meant to say is that I want to map it in a way so that we provide the user with the value from os-release.

**Comment by andy-maier** [comment]
OK, sounds good to me!

**Comment by andy-maier** [comment]
Nir,
unless you are already doing that, I would now start to work on a PR that makes id() reliable as discussed above, and drops base().

**Comment by andy-maier** [comment]
PR #51 does that. Please review.

**Comment by kdeldycke** [comment]
I detailed my solution about distribution groupings at: https://github.com/python-distro/distro/issues/221#issuecomment-4158763641
