### ISSUE TITLE
Cleanup: Unused and public constants in constants.py

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#37]
1. The current code makes no use of the following constants in constants.py:

        LSB_RELEASE = '/etc/lsb-release'
        ARCH_RELEASE = '/etc/arch-release'
        ORACLE_RELEASE = '/etc/oracle-release'
        ENTERPRISE_RELEASE = '/etc/enterprise-release'
        REDHAT_RELEASE = '/etc/redhat-release'   
        CENTOS_RELEASE = '/etc/centos-release'
        DEBIAN_VERSION = '/etc/debian_version'
        FEDORA_RELEASE = '/etc/fedora-release'
        SUSE_RELEASE = '/etc/SuSE-release'
        SLACKWARE_VERSION = '/etc/slackware-version'
        EXHERBO_RELEASE = '/etc/exherbo-release'
        PARALLELS_RELEASE = '/etc/parallels-release'

   I suggest to remove these constants.

2. The remaining constants in constants.py are public:

        UNIXCONFDIR
        OS_RELEASE
        DIST_TO_BASE

   That may or may not be a good idea, so let's review this and they may end up with a leading underscore

**Comment by andy-maier** [comment]
Given that they are technically part of the public interface of the ld module, it seems to me that this should be resolved before the project is declared ready.

**Comment by nir0s** [comment]
They should definitely have an underscore as per https://www.python.org/dev/peps/pep-0008/#global-variable-names. Regarding the others.. I've removed them in #41.
