### ISSUE TITLE
Information from unknown distros is ignored

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#40]
**Problem:**
If a distro has just a distro release file (/etc/*-release) but no /etc/os-release file and no lsb_release command, and if the first part of the file is not one that is known to ld, then the information in that file is ignored, and all ld functions return the empty string.

**Solution:**
I think that should be changed to just accept what such a file provides. That is better than ignoring it.

I think the reason for the filtering to known distros is that on distros that have multiple distro release files (RHEL, Mageia, many others), this is the way how the one to be used is found. But the default case for not finding a known distro could be changed to pick the first file after excluding a few generic ones such as system-release.

**Comment by nir0s** [comment]
So you're suggestion that we look for the first *-release file which isn't a generic one and parse it? That should at least return something allows the user to know that ld did not identify it. Consider a case where it found some arbitrary *-release file that a weird distro decided on or a user decided to inject.. and suddenly you get some weird info there.

**Comment by andy-maier** [comment]
This new approach would only be used for unknown distros (that do no not show up in _DIST_TO_BASE). So if a user injects etc/*-release files into a known distro, that would not change the result.

For unknown distros, a user injecting new /etc/*-release files would cause the result to be changed, that is true. But if that user edits a release file that is used by ld (even for a known distro), the result also gets changed. You cannot project ld from users that are tampering with the distro.

The only problematic case I can see is when a distro not known to ld has some generic release file that ld does not yet have on its ignore list. At that point, we can deal with the issue if users bring it up, either by adding the new generic release file name to ld's ignore list, or by making the new distro one that is known to ld.

**Comment by andy-maier** [comment]
Solved with PR #49. I am closing this issue.
