### ISSUE TITLE
Behavior of _get_dist_from_release_file() if file does not match

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#5]
The docstring says False is returned if the file is not found, but the code does not have a return statement for this case, which causes None to be returned.

I like None for this case much better than False, and therefore suggest to fix the description accordingly.

**Comment by nir0s** [comment]
Fxied docstring https://github.com/nir0s/ld/tree/various-fixes-and-optimizations.
Thanks!

**Comment by andy-maier** [comment]
Thanks for the change!

**Comment by nir0s** [comment]
Solved in 0.2.0
