### ISSUE TITLE
Test with Python 3.4 on Travis CI

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#55]
Travis CI does not run on the Python versions as intended.

For example, [Travis run 52](https://travis-ci.org/nir0s/ld/builds/113070293):

    Python: 2.7     TOX_ENV=flake8
    Python: 2.7     TOX_ENV=py27
    Python: 2.7     TOX_ENV=py26    <- Runs on Python 2.7.9, as per its log
    Python: 3.5     TOX_ENV=py35

In addition (if possible), Travis should also use Python 3.4, because that is stated to be a supported version.

**Comment by nir0s** [comment]
I'm not familiar with Travis supporting 3.4. We need to check that.
Regarding 2.6.. we constantly use it at http://github.com/cloudify-cosmo. If we use tox, declaring "python2.6" in Travis and using py26 as the tox env will test on python 2.6

**Comment by andy-maier** [comment]
OK, I understand the py26 support now: tox sets up a py26 environment in which the test runs, using a py27 system python. I'm fine with that.

The remaining issue is then the Python 3.4 support.
