### ISSUE TITLE
Use of /etc/lsb-release file

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#6]
This file is not part of the LSB standard. Only the lsb_release command is part of the LSB standard. It is defined here: http://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/lsbrelease.html

Therefore, it is valid for a distro to support the lsb_release command without even having an /etc/lsb-release file, or by having one with just the LSB compliance information and the distro information is obtained from elsewhere (RHEL 6.7 is such a case).

You could invoke lsb_release -a once during initialization, and parse its output.

**Comment by andy-maier** [comment]
I have to say though, that the ID returned by the lsb_release command is sometimes weird, if it is not specified as DISTRIB_ID in the /etc/lsb-release file. In that case, the standard implementation of the lsb_release command creates an ID from the distro name in the distro release file, by removing any blanks. On RHEL 6.7 for example, lsb_release -i results in:
    Distributor ID:	RedHatEnterpriseWorkstation
I can see how parsing the /etc/lsb-release file avoids that, but on the other hand, it is simply not part of the LSB standard. Maybe the use of LSB should get lower priority than the use of a distro release file ...

**Comment by nir0s** [comment]
hmm. What about using `/etc/lsb-release` and falling back to `lsb_release` instead?

**Comment by andy-maier** [comment]
In theory, because the LSB standard does not even mention the file, a future implementation of the lsb_release command could use a different format within the /etc/lsb-release file. I would say that is unlikely, but it is not impossible.

One consideration might be: If you have to code the invocation of the command anyway, what value is it to access the file, in addition. The command will access the file anyway. The only advantage of the file-then-command approach I can see is performance (although that might be an important factor - I have read in some forum that minimalistic Linux distros in embedded environments are sensitive even about the file access to the *-release file).

Also, the standard implementation of the lsb_release command does not only parse the /etc/lsb-release file, but in addition stuff in the /etc/lsb-release.d directory, if present. That is used for LSB compliance information. Do you want to support that as well?

Overall, I think I'm still leaning towards just command execution.

**Comment by nir0s** [comment]
Makes sense to go with the `lsb_release -a` command and parse stdout just like parsing os-release.. and provide a dictionary with its values leaving out Description which, like with os-release having additional fields, will be exposed via a `get_lsb_release_attr()` command.

**Comment by nir0s** [comment]
Currently, I've removed any remains of parsing the /etc/lsb-release file and are now only using `lsb_release -a`.

This seems to be owrking well so unless we uncover problems with the current implementation, I see this issue as closed.
