### ISSUE TITLE
Discussion: Non-codename strings in codename fields of distro release files

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#62]
On some distributions, the codename field in the distro release files does not really contain a codename.

Examples:

* openSUSE 42: ``x86_64``
* CentOS 5.1: ``Final``
* CentOS 7.1: ``Core``
* Mageia 5: ``Official``

Currently, the string in the codename field is returned as-is. It is unlikely that there is a good way to handle such non-codenames other than special-casing each such distro. Also, it may well be that applications want to see the value, regardless of what its semantics is.

This issue has been opened in order not to forget about this, and in order to collect opinions about this matter.

**Comment by nir0s** [comment]
Taking into consideration that users might want these values, I think it's good to return it. 

We could handle those specific cases and not return the value in a codename field but rather as extra info which would require additional handling for each distribution.

Off the top of my head, I think we should leave this as is and document that as codename conventions are not consistent, we return whichever value is parsed AS the codename and users can decide how to deal with the data.

**Comment by andy-maier** [comment]
I agree and will create a PR that documents it.
