### ISSUE TITLE
Public elements in the ld module

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#7]
For the following elements, I'm not sure it is a good idea for them to be public:

    get_*_attr()
    set_distribution_properties()
    ldi

Of course, this is up to your consideration.

**Comment by nir0s** [comment]
I've fixed `ldi` and `set_distribution_properties()` but get_*_attr() is meant for users to be able to get additional fields when possible. For instance, os-release sometimes has additional fields which are not exposed via the API directly. What do you think?

**Comment by nir0s** [comment]
For all changes related to the issues you're providing, see https://github.com/nir0s/ld/tree/various-fixes-and-optimizations

**Comment by andy-maier** [comment]
* On ldi: You replaced it with LinuxDistribution().

  I don't think Python optimization goes so far as to use the same object every time (but correct me if I'm wrong here). If it creates different objects, then they are initialized on every access to a field, if one uses the one-by-one methods (e.g. id()). The initialization includes parsing files (and possibly invoking the lsb_release command).

  I like the approach with the global variable much better, from a performance perspective.

* On get_*_attr(): Ok by me. I first thought that having the mechanism-specific *_info() functions would be sufficient, but I agree that having one-by-one access functions is probably a good thing.

**Comment by nir0s** [comment]
True, I don't know what I was thinking. We'll make this `_ldi` instead.

**Comment by nir0s** [comment]
done

**Comment by nir0s** [comment]
solved in 0.2.0
