### ISSUE TITLE
Testcase for Exherbo Linux is missing

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#76]
Exherbo Linux (ID: `exherbo`) is one of the distros with a reliable ID. A testcase should be added.

If you want to help, it is sufficient to post to this issue:
* The content of the `/etc/os-release` file, if any.
* The file names and content of the `/etc/*release` and `/etc/*version` files, if any.
* The output of the command: `lsb_release -a`, if available.

**Comment by Philantrop** [comment]
Exherbo distro dev here.

/etc/os-release:

NAME="Exherbo"
PRETTY_NAME="Exherbo Linux"
ID="exherbo"
ANSI_COLOR="0;32"
HOME_URL="https://www.exherbo.org/"
SUPPORT_URL="irc://irc.freenode.net/#exherbo"
BUG_REPORT_URL="https://bugs.exherbo.org/"

We're a source-base rolling-release distro so there's no meaningful /etc/*release /etc/*version or lsb_release.

**Comment by andy-maier** [comment]
Great, thanks for the input!!

**Comment by andy-maier** [comment]
Created PR #93 that fixes this issue.
