### ISSUE TITLE
name() uses LSB ID

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#8]
In name(), the LSB ID value (distrib_id in /etc/lsb-release) is used to obtain the distro name. Using the lsb_command instead of the lsb-release file (see my other issue), this equates to using its -i option. However, the -d option (description) is better suited for name(), because it returns the human readable name, instead of the machine readable ID.

Be aware that the format of any information item returned by lsb_release is not defined in the LSB standard. However, it seems that the description item often has the format of the one-line distro release file, which may be caused by the fact that in its standard implementation, the lsb_release command looks up that information from the one-line distro release file if not specified in /etc/lsb-release.

**Comment by nir0s** [comment]
Well, once we move to the `lsb_release` command based parsing, this will no longer be a problem.
Regarding the description, I tend to think we shouldn't use it. The base `lsb_release -a` command provides us with `Distributor ID` (i.e. `id`), `Release` (i.e. `version`) and `Codename` (i.e. `codename`) so I think that's enough. If we expose a "get_lsb_release_attr()` method which allows to query the `Description` field, that might suffice.

**Comment by nir0s** [comment]
Comments?

**Comment by andy-maier** [comment]
On ID: It also can map without problems to the first part of the basename of the distro release file, if one is found.

The real decision is on the use of the "Distributor ID" attribute of the lsb_release command. I have not enough data points to have an educated enough opinion, unfortunately (I have only seen it on Debian and Ubuntu, and CentOS/RHEL/Fedora have an additional package that provides the command). In theory, it could map to ID or to NAME, both makes sense from certain perspectives. The attribute name suggests to map it to ID, but I have seen some strange values in it, for example the additional package for RHEL 6.7 has a value of "RedHatEnterpriseWorkstation". This package uses the shell-based implementation of the command, which parses the distro name from the release file and removes spaces from it, to obtain the "Distribution ID" value. Unfortunately, because in the current algorithm, the priority is os-release first, then lsb_release, then distro release, on RHEL 6.7, the reasonable ID derived from the base name of the distro release file gets destroyed by the lsb_release "Distribution ID" value. Maybe we should declare that this priority is broken: If the shell implementation of lsb_release parses the distro file anyway, why not give it a higher priority. That would address the strange mangling, and would allow us to map "Distribution ID" to ID, hoping that in cases where no other file is present, the distro owners would have paid attention to the result of lsb_release.

Following this thinking, the mapping would be (plus some more details):

* id(): ID (os-release) == first part of distro-specific release file == Distributor ID in lsb_release
* name(Pretty=False): NAME (os-release) == distro name within distro-specific release file == Distributor ID in lsb_release
* name(Pretty=True): PRETTY_NAME (os-release) == entire line (NAME+VERSION+CODENAME) of distro-specific file minus the word release in the middle == Description in lsb_release

**Comment by andy-maier** [comment]
The currently implemented use of the various attributes is (in priority order):

  * id(): ID (os-release), Distributor ID in lsb_release, first part of distro-specific release file.
  * name(Pretty=False): NAME (os-release), Distributor ID in lsb_release, distro name within distro-specific release file.
  * name(Pretty=True): PRETTY_NAME (os-release), Description in lsb_release, long name + version + (codename) of distro-specific release file.

I have slightly changed my opinion on this:

1. I believe the currently implemented priority of os-release, then lsb_release, then distro release file is a good one, and we should stick to that priority for all methods / mappings. If we encounter issues of reliability of id() across releases, we could implement a normalization mechanism as discussed in issue #36. Let's resolve that as part of issue #36.

2. The currently implemented source attributes for these three functions are good, with the exception of the use of name(Pretty=False), which uses the Distributor ID from lsb_release, and I think it would be more consistent with the other sources to use the Description from lsb_release, instead. That would be the only change I propose as part of this issue here.

**Comment by andy-maier** [comment]
This issue should be resolved before the project is declared ready.

**Comment by nir0s** [comment]
Good to hear. Regarding your second concern, if you look at `os-release` on, for example, ubuntu 14, you'll see that NAME is Ubuntu and PRETTY_NAME is Ubuntu 14.04.3 LTS.
In lsb_release, ID is Ubuntu and Description is Ubuntu 14.04.3 LTS.

It seems to me like `name(pretty=False)` actually perfectly correspond with `os-release`. Am I missing something?

**Comment by andy-maier** [comment]
Your Ubuntu example indeed is a case that argues for mapping name(pretty=False) to the Distributor ID of lsb_release. I understand that we both agree that name(pretty=False) should map to NAME of os-release.

However, there are other distros where NAME in os-release is not what you would expect from an ID. Here is what we have in the resources/distros subtree:

    RHEL 7.0:       NAME="Red Hat Enterprise Linux Server"
    Arch:           NAME="Arch Linux"
    OpenSUSE 42.1:  NAME="openSUSE Leap"
    Ubuntu 14.04:   NAME="Ubuntu"
    Slackware 14.1: NAME=Slackware
    CentOS 7:       NAME="CentOS Linux"
    Debian 8:       NAME="Debian GNU/Linux"
    Fedora 23:      NAME=Fedora

That's why I brought up the relation to Description of lsb_release. Unfortunately, out of those distros, only two have lsb_release:

    Ubuntu 14.04:   Description: Ubuntu 14.04.3 LTS
    Debian 8:       Description: Debian GNU/Linux 8.2 (jessie)

    Ubuntu 14.04:   Distributor ID:	Ubuntu
    Debian 8:       Distributor ID:	Debian

It seems that both of these attributes are not perfect in some cases. Maybe using Distributor ID is better in these two cases.

Just from my feeling, name(pretty=False) would best map to the lsb_release Description attribute after stripping off the release and codename.

The original problem I brought up is only relevant for distros that have lsb_release but not os-release, so maybe it quickly becomes irrelevant.

Unless this comment caused you to think it over again, I'd be ok with closing this issue.

**Comment by andy-maier** [comment]
Should we close this issue?

**Comment by andy-maier** [comment]
Closing this issue.
If some feels this is relevant, please reopen it.
