### ISSUE TITLE
version() is inconsistent between pretty and non-pretty for os-release file

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#9]
If the os-release file is present, version() with pretty uses its 'version' field, and version() without pretty uses the 'version_id' field.

The 'version' field in os-release may or may not contain anything after the version, and in practice, the format seems to vary. The current code takes care of that for example by special casing the 'version' field in _parse_key_value_files(). In the comma-separated format of the 'version' field for example, version() does not return a string that follows the "version (codename)" format.

So I think the 'version' field should not be used unconditionally. Instead, I suggest to (for the os-release case) always determine the version without codename from the 'version_id' field, and in the pretty case, append " (codename)" as returned by codename():

        version = self.get_os_release_attr('version_id') \
            or self.get_lsb_release_attr('distrib_release') \
            or self.get_dist_release_attr('version_id') \
            or ''
        if pretty and self.codename():
            version = '{0} ({1})'.format(version, self.codename())
            # TODO: Decide whether appending codename to an empty version makes sense.
        return version

**Comment by nir0s** [comment]
wonderful idea.

**Comment by nir0s** [comment]
done in https://github.com/nir0s/ld/tree/various-fixes-and-optimizations

**Comment by andy-maier** [comment]
Saw the code and like the empty version handling. Thanks!

**Comment by nir0s** [comment]
solved in 0.2.0
