### ISSUE TITLE
Should version() continue utilizing version from the name/description fields?

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#95]
Currently, the `version()` function utilizes the version information from the name and description fields of the os-release file and distro release file, if it does not find version information in the usual three sources.

While it is theoretically possible that a distro has version information only in these fields, it is not known whether such a distrio exists. So we could simplify the code by dropping the processing of these two additional sources.

Please provide your review/considerations/wishes about which way to go in this matter, by commenting on this issue.

**Comment by nir0s** [comment]
I'm all for removing unneeded code until we stumble into a case in which we need it. I haven't stumbled into a situation in which the version information is not available in the version fields. So.. i'm in for removing that code.

**Comment by andy-maier** [comment]
With LinuxMint 17, we now have the first distro where the best version comes from the NAME field of the os-release file, so it utilizes one of the two extra functions.

In fact, I found that our current parsing of the pretty versions does not tolerate the trailing `" LTS"` in Ubuntu versions. When I add toleration support for that, we suddenly get a more precise best version also from Ubuntu (14.04.3 instead of 14.04). That also relies on the first extra function that processes the NAME field of the os-release file.

The second extra function processing the Description field of the lsb_release command finds a parseable content of that field for Mageia, LinuxMint, Ubuntu, Debian and kvmibm. However, all of those have the best version available somewhere else with a higher precedence. Yet, it is possible that some distro relies on it.

How about disabling the second extra function because there is no distro known currently that would rely on it, but keeping the first extra function?

**Comment by nir0s** [comment]
Hehe. It seems to me like if I just replied that I think we should remove it, you'd say we found a distro that uses the second one :)

Anyhow, sure. I have no objection here.

**Comment by andy-maier** [comment]
:-) you did :-)
I was about to agree to the removal, and then learned more, today.
Let's keep them for the moment, at least until we have figured out how to special case Linux Mint. Maybe their use becomes part of the special casing.

**Comment by nir0s** [comment]
Should we close this for now?

**Comment by andy-maier** [comment]
Yes, my take would be to close this for now.

**Comment by andy-maier** [comment]
Closing it.
