### ISSUE TITLE
Clarify what distro the normalized distro ID "nexus_centos" belongs to

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#96]
The list of reliable distro IDs in the description of the `id()` function contains an entry with distro ID `nexus_centos`. I was not able to find out what that should be.

If you know what this is supposed to be (e.g. long name of the distro, link to its home page), please provide this by commenting on this issue.

**Comment by nir0s** [comment]
I'm pretty sure it was implemented for a specific customer using Centos to install Nexus by either salt or otherwise. I think it's safe to say we can close this until we get a complaint :)

**Comment by andy-maier** [comment]
Ok, then I'd like to remove its entry from the list of distros for which we state reliable IDs.
I'll create a PR for it.

**Comment by andy-maier** [comment]
Created PR #105 that removes it.
